### ISSUE TITLE
Add local id support

### ISSUE THREAD

**Issue by jackie-greenbaum** [jokiefer/drf-json-api-atomic-operations#8]
I see that there is planned support for local ids as defined in the [JSON API Spec](https://jsonapi.org/format/#document-resource-object-identification) and [Atomic Operations extension spec](https://jsonapi.org/ext/atomic/#operation-objects) per the README

Creating an issue to track the progress of this effort, as it is currently a blocker for our usage of this library.

(Feel free to close this if it conflicts with some other internal tracking for this)

**Comment by jokiefer** [comment]
Nice work. Thx for contributing.

**Comment by jokiefer** [comment]
feature is now available with [v0.4.0](https://pypi.org/project/drf-json-api-atomic-operations/0.4.0/).
